server:
  port: 9191

spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  datasource:
    name: yt_helper
    url: jdbc:mysql://localhost:3306/yt_helper?useUnicode=true&characterEncoding=UTF8
    username: root
    password: accp
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
  mvc:
    static-path-pattern: /**

# 配置数据库
mybatis:
  mapper-locations: "classpath*:mapper/*.xml"
#  logging.level.com.lion.mapper= debug

logging:
  level:
    com.zxt.helper.dao: debug

#分页pageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

#图片识别
tess4j:
  data-path: D:\tessdata
  language: chi_sim



##minio
minio:
  url: 127.0.0.1:9000 #换成自己的minio服务端地址
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: test